Time: 2022/5/29 14:12:00

web异常

--Exceptions--
RedisException => 127.0.0.1:6379
  SocketException => 由于目标计算机积极拒绝，无法连接。 127.0.0.1:6379

--StackTrack--
   在 ServiceStack.Redis.RedisNativeClient.AssertConnectedSocket()
   在 ServiceStack.Redis.RedisNativeClient.AssertServerVersionNumber()
   在 ServiceStack.Redis.RedisClient.GetServerRole()
   在 ServiceStack.Redis.RedisResolver.CreateRedisClient(RedisEndpoint config, Boolean master)
   在 ServiceStack.Redis.RedisResolver.CreateMasterClient(Int32 desiredIndex)
   在 ServiceStack.Redis.PooledRedisClientManager.GetClient()
   在 BK.Cloud.Logic.LogicRedisManage.GetRedisLW(String HasKey) 位置 D:\BKD\BKCLODE\src\Common\BK.Cloud.Logic\LogicRedisManage.cs:行号 21
   在 BK.Cloud.Facade.FacadeRedisManage.GetRedisLW(String key) 位置 D:\BKD\BKCLODE\src\web\Process\ST.Cloud.Facade\FacadeRedisManage.cs:行号 18
   在 BK.Cloud.Web.Webapi.RedisManageController.GetRealCommond(Condition account) 位置 D:\BKD\BKCLODE\src\Common\BK.Cloud.WebApi\Webapi\RedisManageController.cs:行号 31
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
*****************************************************************
